CREATE TABLE payment_orders (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number    VARCHAR(64)    NOT NULL UNIQUE,
    alfa_order_id   VARCHAR(64),
    client_id       BIGINT         NOT NULL REFERENCES users(id),
    membership_type_id BIGINT      NOT NULL REFERENCES membership_types(id),
    amount_kopecks  BIGINT         NOT NULL,
    status          VARCHAR(16)    NOT NULL DEFAULT 'PENDING',
    created_at      TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    paid_at         TIMESTAMP
);

CREATE INDEX idx_payment_orders_client ON payment_orders(client_id);
CREATE INDEX idx_payment_orders_alfa_id ON payment_orders(alfa_order_id);
